//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::F13, // A4 Tacho (IDM)
	Gpio::C7, // A10 AC Clutch
	Gpio::D11, // A12 Injector 3
	Gpio::D10, // A13 Injector 4
	Gpio::D9, // A14 Injector 5
	Gpio::F12, // A15 Injector 6
	Gpio::C9, // A19 Fuel Pump Monitor
	Gpio::G3, // A21 Idle (IAC)
	Gpio::G5, // A22 Low Speed Fuel Pump
	Gpio::G14, // A32 IMRC
	Gpio::C6, // A35 Speed Control Vent Solenoid
	Gpio::B9, // A36 SPOUT
	Gpio::G4, // A41 HFP
	Gpio::C8, // A51 Speed Control Vacuum Solenoid
	Gpio::A8, // A54 WOT Cutout Relay
	Gpio::G6, // A55 FAN
	Gpio::G7, // A58 Injector 1
	Gpio::G8, // A59 Injector 2
// "A4 Tacho (IDM)",
// "A10 AC Clutch",
// "A12 Injector 3",
// "A13 Injector 4",
// "A14 Injector 5",
// "A15 Injector 6",
// "A19 Fuel Pump Monitor",
// "A21 Idle (IAC)",
// "A22 Low Speed Fuel Pump",
// "A32 IMRC",
// "A35 Speed Control Vent Solenoid",
// "A36 SPOUT",
// "A41 HFP",
// "A51 Speed Control Vacuum Solenoid",
// "A54 WOT Cutout Relay",
// "A55 FAN",
// "A58 Injector 1",
// "A59 Injector 2",
}
