//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::F13, // EECIV 4 Tacho (IDM)
	Gpio::C7, // EECIV 10 AC Clutch
	Gpio::D11, // EECIV 12 Injector 3
	Gpio::D10, // EECIV 13 Injector 4
	Gpio::D9, // EECIV 14 Injector 5
	Gpio::F12, // EECIV 15 Injector 6
	Gpio::C9, // EECIV 19 Fuel Pump Monitor
	Gpio::G3, // EECIV 21 Idle (IAC)
	Gpio::G5, // EECIV 22 Low Speed Fuel Pump
	Gpio::G14, // EECIV 32 IMRC
	Gpio::C6, // EECIV 35 Speed Control Vent Solenoid
	Gpio::B9, // EECIV 36 SPOUT
	Gpio::G4, // EECIV 41 High Speed Fuel Pump
	Gpio::C8, // EECIV 51 Speed Control Vacuum Solenoid
	Gpio::A8, // EECIV 54 WOT Cutout Relay
	Gpio::G6, // EECIV 55 FAN
	Gpio::G7, // EECIV 58 Injector 1
	Gpio::G8, // EECIV 59 Injector 2
// "EECIV 4 Tacho (IDM)",
// "EECIV 10 AC Clutch",
// "EECIV 12 Injector 3",
// "EECIV 13 Injector 4",
// "EECIV 14 Injector 5",
// "EECIV 15 Injector 6",
// "EECIV 19 Fuel Pump Monitor",
// "EECIV 21 Idle (IAC)",
// "EECIV 22 Low Speed Fuel Pump",
// "EECIV 32 IMRC",
// "EECIV 35 Speed Control Vent Solenoid",
// "EECIV 36 SPOUT",
// "EECIV 41 High Speed Fuel Pump",
// "EECIV 51 Speed Control Vacuum Solenoid",
// "EECIV 54 WOT Cutout Relay",
// "EECIV 55 FAN",
// "EECIV 58 Injector 1",
// "EECIV 59 Injector 2",
}
